build:
  maxIssues: 10
  excludeCorrectable: false

config:
  validation: true
  warningsAsErrors: false

console-reports:
  active: true

output-reports:
  active: true
  exclude:
    - 'TxtOutputReport'

comments:
  active: true
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false

complexity:
  active: true
  CyclomaticComplexMethod:
    active: true
    threshold: 15
  LongMethod:
    active: true
    threshold: 80
    ignoreAnnotated:
      - 'Composable'
  LongParameterList:
    active: true
    functionThreshold: 6
    constructorThreshold: 7
  LargeClass:
    active: true
    threshold: 600
  TooManyFunctions:
    active: true
    thresholdInFiles: 15
    thresholdInClasses: 15

coroutines:
  active: true
  GlobalCoroutineUsage:
    active: true
  SuspendFunWithFlowReturnType:
    active: true

empty-blocks:
  active: true
  EmptyCatchBlock:
    active: true
  EmptyFunctionBlock:
    active: true
    ignoreOverridden: false

exceptions:
  active: true
  TooGenericExceptionCaught:
    active: true
    exceptionNames:
      - 'ArrayIndexOutOfBoundsException'
      - 'Error'
      - 'Exception'
      - 'IllegalMonitorStateException'
      - 'IndexOutOfBoundsException'
      - 'NullPointerException'
      - 'RuntimeException'
      - 'Throwable'
  PrintStackTrace:
    active: true
  SwallowedException:
    active: true

naming:
  active: true
  ClassNaming:
    active: true
  FunctionNaming:
    active: true
    ignoreAnnotated:
      - 'Composable'
      - 'Test'
      - 'ParameterizedTest'
  PackageNaming:
    active: true
  VariableNaming:
    active: true

performance:
  active: true
  ForEachOnRange:
    active: true

potential-bugs:
  active: true
  EqualsWithHashCodeExist:
    active: true
  UnnecessaryNotNullOperator:
    active: true
  UnnecessarySafeCall:
    active: true
  UnreachableCode:
    active: true

style:
  active: true
  MaxLineLength:
    active: true
    maxLineLength: 120
  MagicNumber:
    active: false
  ReturnCount:
    active: true
    max: 3
    excludedFunctions:
      - 'equals'
    excludeReturnFromLambda: true
  NewLineAtEndOfFile:
    active: true
  UnnecessaryAbstractClass:
    active: false
  UnusedPrivateMember:
    active: true
  UseCheckOrError:
    active: true
  UseRequire:
    active: true
  VarCouldBeVal:
    active: true
